namespace:
  name: staging
 
image:
  repository: nginx
  tag: 1.18.0
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
    
service:
  type: ClusterIP
  port: 8111
 
configmap:
  data:  "version: 1.18.0"
