namespace:
  name: test
 
image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent
  
replicaCount: 3

resources:
  requests:
    memory: "50Mi"
    cpu: "256m"
    
service:
  type: ClusterIP
  port: 8111
 
configmap:
  data: "version: alpine"
