namespace:
  name: prod
 
image:
  repository: nginx
  tag: 1.17.0
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    memory: 256Mi
    cpu: 70m
    
service:
  type: ClusterIP
  port: 80
 
configmap:
  data: "version: 1.17.0"
