  
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    tag: alpine
  name: nginx-alpine
  namespace: {{ Values.namespace.value }}
spec:
  replicas: {{ Values.replica.count }}
  selector:
    matchLabels:
      app: nginx
      tag: alpine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
        tag: alpine
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: {{ Values.image.pullpolicy }}
        name: {{ Values.image.name }}
